#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Build train/dev/test TSVs   +   3 human-readable debug files
(dropped_comments.txt, diffs_label1.txt, diffs_label0.txt).

• TSVs     → repo root
• Debug    → ./debugging_files/
"""

import os, re, json, random, atexit
from typing import List, Tuple, Dict, Set
from rapidfuzz import fuzz
from tqdm import tqdm

# ───────────────────────────────────────────────────────────────────────
# KEEP YOUR FULL GENERIC_EXAMPLES  &  SHORT_MAX_LEN  TABLES UNCHANGED!
GENERIC_EXAMPLES: List[str] = [
    "Applied.",
    "Sorry!",
    "Yeah that is probably better. Thanks. I updated the patch.",
    "Use poison",
    "takeName",
    "Side hack, probably shouldn't do this here",
    "```suggestion```Noise",
    "Fixed",
    "I'll post that tomorrow in the hope that the build bots have calmed down by then, since precommit seems to be failing for everyone atm",
    "I think there are two things going on here:",
    "Nit: `m_`?",
    "The main changes are here.",
    "This is the type of typo this can help prevent!",
    "Nice!",
    "Seems like this variant is unnecessary.",
    "nit: What is this needed for?",
    "Delete this line as it's irrelevant to this patch?",
    "Delete both lines?",
    "Thank you for the suggestion; I’ll take it into consideration.",
    "Braces",
    "also here",
    "Didn't see, thank you",
    "Thanks. I think it's fine either way.",
    "This should have a different text.",
    "I've added some tests with different attributes in different places. If you have any idea what should be added - small example (just code line) would be appreciated.",
    "Thanks, fixed. Now it mention that empty function also merged.",
    "Thanks, fixed",
    "fixed",
    "Pushed a correction. It still passes here locally.",
    "Thank you.",
    "Should we also send notification on Discord?",
    "Maybe on discord, just send a link to the discourse thread? IMHO, it is better to only have to manage one thread.",
    "```suggestion\n}\n\n```",
    "This is kind of worse",
    "whether",
    "Done. Thanks for the finding.",
    "Thank you for the link!",
    "Thank you for the link!\n\nDone.",
    "Agree. Early return is a good idea here.",
    "Done.\n\nIt looks better now.\n\nThank you!",
    "Good idea, done.",
    "Comment",
    "Correct, I forgot to add one. Will add.",
    "`false`?",
    "Ditto.",
    "yes, thanks for the notice",
    "typo: \"sanboxir\"",
    "Fixed.",
    "I've added those tests now.",
    "Ah! I've removed the escape. :-)",
    "Unrelated?",
    "Ok, makes sense. Just pushed something.",
    "ok, done!",
    "Done.",
    "This was the primary goal of this PR.",
    "Oops yes, removed",
    "Okay, I see. I'll amend it.",
    "This does not look obvious to me. Can you explain?",
    "I fixed that / added comments",
    "Can we add some comments? what causes us to change it from 24 -> 32",
    "another typo :)",
    "Thanks for the finding. Done",
    "Thanks for the hint. That makes more sense. Feel free to check the corresponding commits.",
    "Thank you for the explanations. Am I right in assuming that we can leave it as it is for this PR?",
    "I think it's good as-is. Thanks.",
    "oh yes, thanks",
    "fixed in main, thanks",
    "Sounds good! Worth adding a comment explaining that so others don't wonder as well.",
    "Actually, I don't see it anymore.  Good then.",
    "Sounds good! That seems to also be how we do it elsewhere in the codebase",
    "Nit: Update comment above.",
    "Yes, this seems clear.",
    "Updated",
    "Changed to suggestion",
    "Added comment",
    "Added test for upper limit",
    "OK, I'll take into account when implementing next intrinsics.",
    "I tried that fix, and I agree it looks like the right fix to me. It seems to solve the issue.",
    "https://github.com/llvm/llvm-project/pull/133840",
    "```suggestion\n```",
    "Ahh, got it.",
    "yep, changing it now",
    "This looks to be resolve, but not done.",
    "Thanks a lot for the comment!",
    "Done.",
    "done!",
    "also here",
    "(see comment above)",
    "Yes, that will work.",
    "Not really relevant here, and redundant with the final result check",
    "Yea, updated.",
    "same here",
    "You're right. I created https://github.com/llvm/llvm-project/pull/133370",
    "What's all this about?",
    "Oops needed to remove that",
    "Nit: newline",
    "moved it back",
    "remove?",
    "hahah, epic explanation!",
    "Removed",
    "This is already tested in mlir/test/Dialect/LLVMIR/func.mlir",
    "I see. This makes sense. Thanks for clarifying.",
    "unrelated?",
    "unnecessary",
    "remove",
    "unrelated",
    "Done.",
    "Yes, improved. Added more check lines to show that.",
    "Sorry, I'm too spoiled with Python 3.12 on my job :-)",
    "Same here.",
    "Good catch! Will add tomorrow.",
    "ahh, didn't read the full code.",
    "That's great to know!",
    "What's this for?",
    "Good call, that exposed an issue. I'll add test coverage and correct the problem.",
    "Absolutely!",
    "Fair point!",
    "I'm blind!",
    "Sure, added!",
    "Sure",
    "You are right. Fixed in the latest revision.",
    "done, but what's the difference?",
    "or false, whichever.",
    "Ok, yeah that makes sense.",
    "Makes sense, thanks for explaining!",
    "This still worries me.",
    "What do you expect here?",
    "Ok, will do actual cost estimation",
    "Done.",
    "Ok. Thanks for checking.",
    "ditto",
    "Thanks ! I didn't know they could be implicit.",
    "Nope. :-(\nBut now fixed.",
    "correct",
    "This also unintentionally?",
    "Is this left unintentionally?",
    "Good idea.",
    "Removed.",
    "I trimmed most of the comments.",
    "Thanks, will do.",
    "Ohh I see what you mean now. Thanks",
    "I think this could use a comment",
    "Why remove the comment?",
    "(I mailed core)",
    "@zygoloid",
    "Here too perhaps?",
    "They're not, I'll add this as a test case.",
    "I'll add test coverage",
    "Ah, yeah, makes sense",
    "Was this a previous bug?",
    "I have to say that is a choice.",
    "Thank you for the feedback. Will do.",
    "Sure, good call!",
    "Surely you mean 21?",
    "Thank you, I wasn't sure how this work related to releases. I fixed it.",
    "thank you for the review. I have removed extra line.",
    "Thank you for the suggestion! I've added a [comment ](https://github.com/llvm/llvm-project/issues/128656#issuecomment-2753046448) in the issue #128656 to track these TODO tasks.",
    "You are right! Correcting now.",
    "this as well",
    "yes. will do",
    "will remove it",
    "Oh, that's actually not used, I should get rid of it thanks!",
    "https://github.com/llvm/llvm-project/pull/133633",
    "Also here",
    "I agree, I'll revert these changes.",
    "I have kept it as-is if you don't mind.",
    "And this key is new.",
    "I don't think this is necessary.",
    "Sure, I'll do that.",
    "add negative test",
    "Is this supposed to be on 2 lines?",
    "good catch. no this should be one line",
    "Good points, thank you! I've updated the PR accordingly.",
    "That sounds great to me, I'd support that",
    "Fixed in latest diff.",
    "newline :)",
    "Is this being used somewhere?",
    "Fixed this.",
    "Fixed that.",
    "Yup, fixed that.",
    "No, idk how that got added. Deleted it.",
    "Fixed.",
    "Fair enough, I reverted this file.",
    "And this key is new.",
    "I don't think this is necessary.",
    "Sure, I'll do that.",
    "add negative test",
    "good catch. no this should be one line",
    "Good points, thank you! I've updated the PR accordingly.",
    "Fixed in latest diff.",
    "Thanks, fixed",
    "Changes applied Let me know if it looks good now",
    "Sure.",
    "This has been fixed.",
    "Done.  This preserves consistency.",
    "Ok. I can update it this way.",
    "Added",
    "Fixed, thanks!",
    "removed!",
    "Fixed, thanks!",
    "Here and below.",
    "Thanks, should be addressed now",
    "Okay feel free to ignore my comment then",
    "It shouldn't.",
    "Ah, right",
    "Code updated",
    "This is worse",
    "No problem.",
    "Please ignore.",
    "What is this for?",
    "Skipped for now: https://github.com/llvm/llvm-project/commit/d4002b43f517fea0292bf71dccaa3d0f6dd798b9",
    "parameters",
    "Woops, removed!",
    "Good point, removed",
    "You're right, sorry. I've fixed this now.",
    "Thanks, that makes sense. I've renamed this.",
    "Done, apologies for the noise.",
    "This needs to be updated",
    "Same thing with header here",
    "@Moxinilian",
    "I think i have something cleaner let me know in the new pr.",
    "Ah yeah, I read that wrong. Thanks for confirming.",
    "That's a great point and I really appreciate the suggestion. In fact, I wasn't sure how to do it : ) That's now been incorporated.",
    "Yeah that is probably better. Thanks. I updated the patch.",
    "Yeah. That's ok",
    "Awesome. Thank you!",
    "I never noticed this. Thanks!",
    "Ignore that.",
    "Ignore this",
    "if (inserted)",
	  "When would this not be true?",
	  "Does it look good now? Or should I change more?",
	  "So, once it's enabled it can no longer be disabled? Could we send some sort of an event when the setting changes?",
	  "Typo becauase",
	  "Not a bug of this problem:",
	  "The actual lowering for this is:",
	  "source files as well). However, compile time performance will be slow if there are",
	  "Note to self: stopped review here.",
	  "I agree this is the right test update.",
	  "Just checking, was there nothing for 9.1?",
	  "Thanks, i've incorporated both of these comments.",
	  "Yes, it should be renamed as well.",
	  "Yeah its generated. I copied this from the outputed hlsls test cases. I can update the test cases.",
	  "that's really great point, adding another test.",
	  "There are more similar patterns.",
	  "I have a try something like",
	  "This can also be simplified into:",
	  "Hm, is this case possible?",
	  "Thanks. I'll revert this back.",
	  "Yes, it's LEA at line 10.",
	  "Thanks, can you add it to the PR description?",
	  "This line should be part of the previous paragraph.",
	  "Acknowledged.",
	  "ach, beat me to it!",
	  "Yes, this is the implementation of the traits for OpenMPI.",
	  "Dropped, thanks.",
	  "Thanks, weird that clang-format did not catch this one :(",
	  "Right, good point.",
	  "indeed, will add them",
	  "I probably need to update this test to be align 8.",
	  "My bad, missed it!",
	  "Yes, it's already covered at line 874.",
	  "Same as other function",
	  "DEPENDS",
	  "}",
	  "Yeah, looks great.",
	  "Ah yes ok I am with you.",
	  "Yes, we can fix this later.",
	  "Thanks for finding this.",
	  "Can you help me understand this check?",
	  "The code is fine.",
	  "Will do.",
	  "These should be implicit as well.",
	  "Ah, yes! Moved it to an assert.",
	  "same nit from above",
	  "My justification would be the same.",
	  "I think you can combine these two lines into one.",
	  "Oh yeah of course.. Thanks!",
	  "Fair enough",
	  "Corrected",
	  "I like this idea too.",
	  "Don't think this is needed.",
	  "As above",
	  "Oops, will fix and will check for typo.",
	  "Ah that's better.",
	  "Yep, will fix",
	  "Oh right!",
	  "Works for me",
	  "Oops,  it looks like I forgot to push one commit.",
	  "Adjusted, thanks!",
	  "Yeah you're right, not a problem then.",
	  "This can be an assert",
	  "Please could you link me to the source for this? I am having trouble finding it.",
	  "Dropped, thanks!",
	  "Oh, ok.",
	  "Will rename them.",
	  "Yes, it should.",
	  "Didn't get that?",
	  "I'll write another test.",
	  "Ta!",
	  "likewise",
	  "Thanks for the clarification.",
	  "Aligned.",
	  "-------",
	  "Understood, will address.",
	  "What happened to Example 3?",
	  "Oops, thanks for catching this serious error! Checks have now been tightened.",
	  "Looks reasonable to me.",
	  "LGTM either way",
	  "I don't think so.",
	  "Yes, you are right...",
	  "Good spot!",
	  "@erichkeane @AaronBallman",
	  "I missed this, thanks for noticing.",
	  "Ah yep. :/",
	  "expects",
	  "Outlined, thanks!",
	  "insert",
	  "see #102118",
	  "Oh woops, that should be inverted",
	  "Yeah, I missed this. Will fix.",
	  "I see, thanks for the clarification.",
	  "Good catch, DYN is the default FRM value now.",
	  "I agree this is the right test update.",
	  "Yeah, I think it's good that you raised it, especially because I had the exact same back and forth. I'll leave this conversation as unresolved and maybe fmayer has an opinion.Yeah, I think it's good that you raised it, especially because I had the exact same back and forth. I'll leave this conversation as unresolved and maybe fmayer has an opinion.",
	  "Yes and I should note that.",
	  "reduces",
	  "Even better :)",
	  "Hmmm good question",
	  "This logic still applies.",
	  "Ok, but, suppose that someone has written",
	  "Reordered, thanks!",
	  "Not in this patch",
	  "Will do.",
	  "Add a message",
	  "@clayborg",
	  "Yes, that looks good.",
	  "Did you submit it?",
	  "i see. fixing it.",
	  "same in line 52",
	  "Good job.",
	  "Ah, I see :+1:",
	  "Hi Jonathan,",
	  "Change the 12?",
	  "Okay, thanks in advance.",
	  "Maybe?",
	  "OKie!",
	  "I don't think we need that change",
	  "Something like that.",
	  "@jayfoad ping.",
	  "You are really fast.",
	  "Hi Adam,",
	  "Ok, sounds good to me.",
	  "Ok, looks good to me.",
	  "Oh my :)",
	  "As above.",
	  "This is wrong",
	  "Gone, thanks",
     "Thanks for the pointer and explanation!",
	  "{",
	  "Thanks, I will modify it.",
	  "Do you mean something else?",
	  "That sounds reasonable to me.",
	  "static",
	  "This file needs hi tests.",
	  "Thanks, that is indeed the case.",
	  "Got it, thanks.",
	  "This is probably better",
	  "Good catch. Thanks.",
	  "I can live with that :)",
	  "}",
	  "Thanks for your reminding. I have pre-commited the test.",
	  "You are right. This is no longer needed.",
	  "1. Sounds good.",
	  "Why is this necessary?",
	  "Can do ",
	  "could you elaborate on what are those? I don't know what you mean.",
	  "Good point, I'll create a follow-up PR.",
	  "Please merge with previous entry.",
	  "yes that would be fine by me.",
	  "Similar here",
	  "Thanks for the heads-up! :)",
	  "add a new line",
	  "e.g,",
	  "in the same module.",
	  "please do! thanks!",
	  "Indeed. Amended.",
	  "This is #115659.",
	  "Do you insist?",
	  "ok. got it",
	  "True, that.",
	  "Ack, got it.",
	  "Expanded comments.",
	  "should be fine now",
	  "Thanks, I just did that.",
	  "I changed to what you suggested.",
	  "Undone, thanks",
	  "Yes, that makes sense. Thanks for the explanation.",
	  "cheap trick",
	  "untested",
	  "what does this mean?",
	  "Yes, just replaced it.",
	  "Document this",
	  "Thanks for elaborating",
	  "e.g,",
	  "Thanks! Good catch!",
	  "Simplified, thanks!",
	  "Yes, I guess 6 is enough.",
	  "Missed one",
	  "Commented code.",
	  "Right. I will fix it.",
	  "@cor3ntin ^",
	  "Or this.",
	  "Yes, that's the change I proposed.",
	  "?Where is this used",
	  "Also LGTM!",
	  "@Meinersbur",
	  "fix comments",
	  "Ah. Good to know.",
	  "yes, indeed",
	  "So much better ",
	  "I think these aren't used now.",
	  "Missing test.",
	  "update test title",
	  "Ok.I see.",
	  "OK I will test them in a followup path.",
	  "thanks. changed to AnyShaped.",
	  "Implemented in b491cb6.",
	  "Just a drive-by note.",
	  "Yep that looks good to me.",
	  "Addressed all, thanks",
	  "Latest version is 5",
	  "Use input rank instead of `6`",
	  "Thanks for your comments! I will track them later.",
	  "Good catch, yes this should be private.",
	  "unsigned Size;",
	  "Multiple lines",
	  "Yes, technically. I've dropped the NFC tag.",
	  "Ah?  so we still expect the others to get here?",
	  "This code is in desperate need of some comments.",
	  "Hasn't landed yet.",
	  "Changed, thanks!",
	  "80 characters",
	  "R, State, OrigLoop,",
	  "Whoops.",
	  "Ah, I missed this. I was going to discuss removing this argument as I can't find anything that makes use of it.",
	  "Yess.",
	  "Make it fit in a line (80-char)",
	  "Aha, should be a copy-paste mistake.",
	  "I guess yes, if such an instruction existed.",
	  "Yeah it looks OK, they should both be about the same.",
	  "there are four methods listed",
	  "Very cool.. I do the same.",
	  "Add assertion message",
	  "Oh, missed to update.",
	  "See my comments above.",
	  "Thanks for the pointer and explanation!",
	  "This looks like an improvement.",
	  "Thanks for your reply , I understand it. I'll fix my PR follows the v1.0 Spec.",
	  "e.g,",
	  "Ignore me again.",
	  "Thanks for your comments.",
	  "OK we can do without this",
	  "Agreed, I will raise it.",
	  " Make sense to me.",
	  "Hmm...actually, I was wrong. I must have messed up the calculation. I'll try to catch this usage.",
	  "Thanks, the changes have been made.",
	  "Thanks, I will modify it.",
	  "consider",
    "I never do that!",
	  "Shouldn't this be the other way round?",
	  "Does #114916 help?",
	  "definitely",
	  "Are you working on a follow-up PR or what's the plan otherwise?",
	  "Duplicate line",
	  "Fine with me",
	  "Your wish is my command. :-)",
	  "Can that happen or should we assert?",
	  "Thanks for letting me know @mikerice1969! I'll take care of it",
	  "those changes are no longer in this PR.",
	  "I'll try to add it",
	  "Why did this change?",
	  "Seems reasonable to me.",
	  "Thanks.",
	  "Oh well, good enough!",
	  "That looks fine, thanks",
	  "Common problem.",
	  "Good point, renamed",
	  "We don't do this in most of the code.",
	  "Please give me some time to investigate, I'm not very familiar with analyzer.",
	  "Let's discuss there, thanks!",
	  "Thanks @AaronBallman, updates provided.",
	  "Combining these looks great, thanks.",
	  "Implemented, thanks.",
	  "Thanks for the catch",
	  "Okay, I've reverted back to the old form.",
	  "Thanks! I'm lean towards incremental development and progress, so let's proceed and land this and refactor to align.",
	  "Aah. missed to push this change. Thanks.",
	  "Good point, thanks.",
	  "There still only seems to be one commit in this PR",
	  "Thanks, that wasn't my intention.",
	  "@delcypher Thanks! LGTM.",
	  "Thanks!",
	  "Thanks for the ping. Agree with the inconsistency. Will get back to you.",
	  "Thanks.  It's  more accurate and cleaner.",
	  "Thanks! I will have a look at that on Monday then.",
	  "Sounds good, thanks for the explanation of how we're choosing the minimum supported version.",
	  "Yep, sounds reasonable. Thanks.",
	  "Yes, thanks for catching!",
	  "Thanks! Would you be okay if I do this in an (immediate) follow-up?",
	  "Moved, thanks!",
	  "@AaronBallman thanks for the feedback. Do you mean the [following changes](https://github.com/llvm/llvm-project/pull/112081/commits/9c2a745ed365449be45cd062f29c89cabde0f514)?",
	  "I'll try to remember that in the future.",
	  "You're right, thanks. #111347",
	  "Thanks, I will update that, please let me know if there are any other C++ 26 features that I should adopt.",
	  "Right. Thanks.",
	  "hat worked Thanks!",
	  "Oh perfect, thanks!",
	  "Recovered original style. Please help check if you have other questions about this pr, thanks a lot. :-)",
	  "Thanks, I forgot about this while switching between projects",
	  "Thanks for taking a look.",
	  " did a small bit of refactoring based on Sean's comments to reduce the number of ifdefs now, thanks!",
	  "",
	  "Ack, I'll take care of of it. Thanks.",
	  "Thanks. Just in case, is i12**7** a typo or intentional?",
	  "So try to match them?",
	  "Right, thanks.",
	  "Thanks for the catch",
	  "Yep, moved out, thanks!",
	  "Thanks for the catch, and yup I believe so. They should be clearer now that I have full matches. See update.",
	  "Thanks! I documented those are experimental.",
	  "Thanks. Will fix.",
	  "Ah! Much nicer. Thanks. :-)",
	  "Yes, moved to the top as suggested, thanks!",
	  "Thanks! Swapped the order of the cost. Would you mind doing the merge?",
	  "in the same module.",
	  "Really appreciate this block of comments. Paints the picture of what happens clearly. Thanks :)!",
	  "makes sense, thanks @michaelmaitland and @topperc !",
	  "Thanks, this is now addressed in commit a05ae62",
	  "Yeah, I agree that this patch should not fix those dependencies. Thanks for explaining.",
	  "Ah yeah, there are a couple of them left, I forgot to fix them, thanks for noticing it!",
	  "Oh. Thanks I see.",
	  "Ooops! Thanks for spotting that.",
	  "Yep, moved out, thanks!",
	  "Thanks -- will keep the idea of matching once and reusing the result in mind if performance becomes an issue later!",
	  "Ah, okay, didn't realise that, thanks!",
	  "Swapped and documented ,thanks.",
	  "Oh, I didn't know that. Thanks!",
	  "Restored, thanks!",
	  "Thanks, replaced in https://github.com/llvm/llvm-project/pull/126008/commits/d4cb8efac8dc49197623e99229cf3d8f41335bbc",
	  "Makes sense to me. Thanks for the investigation!",
	  "Thanks for explaining. I had misunderstood what these were for.",
	  "You are right. We can use 2 here.",
	  "The line table without your changes was helpful, thanks!",
	  "thanks, is it possible to add a test?",
	  "Thanks for cleaning these up :)",
	  "I will fix that.",
	  "Separate patch is fine.",
	  "Thanks for this info! Will keep these style rules in mind.",
	  "Yep, moved out, thanks!",
	  "Replaced, thanks!",
	  "hat PR looks good to me, thanks!",
	  "Thanks, I didn't notice that.",
	  "It should. Thanks for catching that.",
	  "#110885",
	  "No bad change! Thanks for catching it!",
	  "Okay, I'll change it to that.",
	  "They are needed.",
	  "Thanks, I've rewritten this to be more explicit about the goals and mechanisms in light of our discussion.",
	  "Sounds good, I'll have a look later then. Thanks :)",
	  "Thanks for linking me to this!",
	  "No bad change! Thanks for catching it!",
	  "DEPENDS",
	  "Yep, will look into that separately, thanks",
	  "Okay Thanks I am Working on it",
	  "Yeah, the original one is much better.",
	  "Is it used somewhere?",
	  "Found a better solution.",
	  "Might as well",
	  "Agreed. Thanks for explaining.",
	  "Thanks looks good to me now!",
	  "Oh, thanks for pointing out this. I'll fix it.",
	  "Thanks for the suggestions! I think they improves readability.",
	  "Hi, I think you're right, thanks. I'll have a look.",
	  "Thanks for the suggestions. I modified the checks as suggested.",
	  "Thanks. Virginia is fixing this in her PR, which this PR is based on.",
	  "Thanks, will look into it as follow-up.",
	  "Not needed in the latest version, thanks",
	  "Ok, thanks for clarifying. I will look into this.",
	  "Thanks for all the reviews @frederick-vs-ja! I will look into it soon.",
	  "What's fake about it?",
	  "Thanks for spotting and the revert. Fix is at https://github.com/llvm/llvm-project/pull/121918.",
	  "That's much better, thanks.",
	  "Didn't know that, thanks.",
	  "Thanks for making the update here.",
	  "oh, I see why now. anyway, thanks!",
	  "Indeed, thanks for the catch.",
	  "In this patch might be simpler thanks.",
	  "Yep, thanks for the catch.",
	  "Update to check #of successors, thanks!",
	  "I've put up https://github.com/llvm/llvm-project/pull/95083 to fix this.",
	  "Make sense, thanks.",
	  "Thanks for the catch",
	  "Moved to the end. thanks!",
	  "An example of regression here.",
	  "Thanks for pointing to the coding standards!",
	  "My motivation was to simplifiy the solution, I will check the other way, thanks.",
	  "};",
	  "Ah, that was the intent. Thanks for pointing it out.",
	  "understood, thanks",
	  "Thanks, I'll update this.",
	  "Thanks. Just in case, is i12**7** a typo or intentional?",
	  "Thanks for your contribution, @fschlimb .",
	  "That seems fine, thanks",
	  "Thanks, did this, including moving some of the other recent, related additions.",
	  "Right. Thanks.",
	  "That looks fine, thanks",
	  "Thanks for the ping. Agree with the inconsistency. Will get back to you.",
	  "You are right, thanks!",
	  "Ah I forgot we don't handle loads and stores yet, thanks for submitting that. I don't see any reason why we can't handle them too.",
	  "I'd prefer to leave it for later.",
	  "Sounds good, thanks!",
    "Ah, I read the original wording wrong, I'll drop this sentence entirely.",
	  "Not a huge deal, just tends to be cleaner.",
	  "And now you can delete all of this",
	  "Yes, that would be cool!",
	  "WTF is a dependent BMI?",
	  "uhh I think so? Its hard to give this thing a precise name",
	  "These shouldn't be here.",
	  "Code gone now",
	  "Please document.",
	  "No. This has no relation to spilling.",
	  "Hi.",
	  "SG, I'll move it.",
	  "Ooo interesting.",
	  "OK.",
	  "I guess you dont need this.",
	  "Will need update after #114061",
	  "I guess this piece is gone.",
	  "Either way is fine by me.",
	  "Please fix FIXME",
	  "@DavidTruby I think you missed this when responding to feedback",
	  "Yes please, so we can keep the test as it was.",
	  "right, typo",
	  "",
	  "Yes it is. I guess I can change this to assert.",
	  "Go for it, then.  Downstream usage can adapt if needed.",
	  "I see - yes.",
	  "Can we",
	  "Changed all places.",
	  "Yeah, we should do that.",
	  "RIght, let's leave it as is then.",
	  "}",
	  "Agreed. Don't think we want to maintain this list.",
	  "Meh",
	  "Do you still need these changes?",
	  "Ping @cxy-1993",
	  "Awe, I thought this was clever/useful :)",
	  "Addressed in dbe8d4c.",
	  "we still need",
	  "This todo should probably be in the code :)",
	  "second this.",
	  "Wrong instruction. Fixing real quick.",
	  "Please restore the comments from the left (extending them if necessary).",
	  "I'm using",
	  "I will try to explain in detail why it was needed :)",
	  "This cannot fail",
	  "This is the second part of the fix.",
	  ") {",
	  "Yeah, this looks much better now.",
	  "Please actually generate the test checks...",
	  "happening.",
	  "in the same module.",
	  "N/A anymore.",
	  "Anyway, I changed as you suggested.",
	  "Yeah, we should do that.",
	  "Yes, I prefer that too.",
	  "Yes, working on updating accordingly",
	  "I think that makes sense ",
	  "That was blind copy-and-paste.",
	  "Nope, I don't mind.",
	  "happening.",
	  "Sounds better IMO",
	  "Yes, I think so.",
	  "It's not. I'm gonna fix it today.",
	  "change to match above",
	  "Yes please, so we can keep the test as it was.",
	  "Yes, testing this also in the latest revision.",
	  "If possible, I would like this to be a separate PR.",
	  "Undo this change?",
	  "Good point. I'll rename this function.",
	  "Alright, for the future roadmap",
	  "Why is this needed now?",
	  "Err yeah :)",
	  "Okay, then I agree that it wouldn't be beneficial to do so.",
	  "That's fine then.",
	  "Got it. The check will be in other PR.",
	  "This seems useful",
	  "Yeah, I think so.",
	  "CC @JDevlieghere who might know more.",
	  "Regenerate this file?",
	  "in the same module.",
	  "This is still an issue.",
	  "OK, if it's pre-checked the unreachable before was fine",
	  "Don't need the mattrs",
	  "Don't need the mattrs",
	  "... I'm confused. Why're you setting all the indices to 0?",
	  "Sounds good. I may experiment with that as part of the effort to improve stale matching/continuous mode.",
	  "Yes, I think that's basically it.",
	  "I'll update that in a separate PR.",
	  "Oh, where is the non-vp version? Or does it exist? :-)",
	  "I don't think we can spell that",
	  "I do not think you need to copy:",
	  "Why was this moved here?",
	  "It's copied from above, and that was also unescaped, good catch",
	  "Cleaned up the code. Hopefully better now.",
	  "Yes, separate patch",
	  "yes. clarified.",
	  "#104864",
	  "Just take name?",
	  "I see your point. I will adjust it to only report the debug message and return true.",
	  "Why was this moved here?",
	  "just renaming",
	  "fixed",
	  "Do you need to make the copy if you're not going to delete it?",
	  "Again, not your fault but it's downright confusing!",
	  "This value is discarded.",
	  "yes, that is a good approach. As long as we know that we won't get an error if some bytes were written",
	  "Good catch. I need to change line 61.",
	  "Why no match? I don't see any trouble with",
	  "Made some improvements.",
	  "Will add the extra check",
	  "Copy-paste != fixing existing mistakes :)",
	  "I could but why?",
	  "Ah, I had missed that!",
	  "ok, sounds justified.",
	  "Keep this all as Align?",
	  "Aha I see, this is a fix. Never mind.",
	  "Ah, I read the original wording wrong, I'll drop this sentence entirely.",
	  "Please add test cases that cover possible errors.",
	  "You're right, I've turned this into a check and brought back the debug print from the original code.",
	  "love this formula! so clever :)",
	  "Then drop them completely from the list",
	  "Neat!",
	  "Yes the owning header should be first",
	  "I hate this thing.",
	  "represnent",
	  "For reach?",
	  "@jrtc27",
	  "Let's move that out, too :)",
	  "I don't think this is reachable.",
	  "There's another hard tab here.",
	  "I looked, but couldn't find anI looked, but couldn't find an",
	  "Cool, makes sense! I'll have to give it a go at some point",
	  "Good catch! I will add a guard here!",
	  "Ah, I see. Sounds good.",
	  "Yes I did.",
	  "Why was this deleted?",
	  "Yes, this was a bug.",
	  "And now you can delete all of this",
	  "This is #114867.",
	  "Also adjusted.",
	  "@jrtc27",
	  "Makes sense.",
	  "Yes, please have a look.",
	  "Yes, that's a better name.",
	  "Typo optimised :)",
	  "Always and Leave?",
	  "I believe this can stay",
	  "Yes I agree. I will add it here.",
	  "Yes, I do remember something related. That's why it is just a question. :)",
	  "Actually I think they're all wrong",
	  "No worries.",
    "line 168 can be hoisted out to the outmost loop (i.e line 163)",
	  "No error message will emit here.",
	  "This was painful to update.",
	  "Did you get a chance to look into this?",
	  "# Title",
	  "Noise in the diff?",
	  "Note moved up to the top of the section.",
	  "Same below.",
	  "DEPENDS",
	  "221a65def345",
	  "Have redone the comments throughout to be clearer.",
	  "Yes exactly",
	  "Yes I thought the same thing, will adjust separately.",
	  "Ahh, that's not great.",
	  "P3074 has been accepted!",
	  "why did you delete all these tests?",
	  "In the future please move such changes to separate patches.",
	  "We should have tests for these.",
	  "yes, oops, fixed!",
	  "explained",
	  "Yes, I removed them now.",
	  "@lukel97 Thank you for the comment.",
	  "3b527754bfb3a3e27cd729d15f511608e2f7f367",
	  "Duplicate comment here.",
	  "Why this change?",
	  "This was a left-over from earlier versions, removed, thanks!",
	  "Ah, that explains it. Thanks!Ah, that explains it. Thanks!",
	  "All looks good, thanks!",
	  "Oh thanks for catching that, I guess it doesn't show up with clang. Will rename!",
	  "Thanks for the review and pointers! 2 seems good to me too, I'm happy to give it a stab.",
	  "Updated as suggested thanks!",
	  "No, leftovers from an earlier version of the code. Removed. Thanks!",
	  "Thanks for pointing this out, done",
	  "Thanks, removed.",
	  "Thanks! That is super helpful, I added the comment.",
	  "Changed.",
	  "Thanks, done.",
	  "Yes, the goal is to not crash. But I added a check for the metadata also, for completeness.",
	  "Do we have a test for",
	  "This cost seems way too big",
	  "Good idea, thanks!",
	  "Thanks, this is done in the following commit https://github.com/llvm/llvm-project/pull/101024/commits/56d599c2faeaf36f2076b40e30cb8e9b15a101ca",
	  "Updated thanks!",
	  "i don't get this.",
	  "This is slightly hack. Let's add a new case for it and maybe we need to update the state machine if required.",
	  "more cases. At the moment, for the following loop nest, even though both loops are",
	  "Added in the latest version, thanks!",
	  "Thanks for the updates - this looks good to me now!",
	  "Good point, it's fixed now.",
	  "Thanks. Done.",
	  "Yep, good suggestion. Thanks!",
	  "const?",
	  "Ack, thanks.",
	  "Make sense, leave it as is then.",
	  "unneeded thanks to llvm/test/MC/Mips/lit.local.cfg",
	  "That's a mistake on my part. Thanks for spotting",
	  "Would we be able to remove this entirely?",
	  "as well as expected",
	  "Yep, better.",
	  "@madhur13490  Thanks for your comment.",
	  "Fixed, thanks, see 2b12acbde48f534e725a1febf1607178266bb3b1",
	  "typically",
	  "See comment regarding similar usage above.",
	  "yes they are, my bad.",
	  "I think that is ok.",
	  "Right! Good idea.",
	  "Please add a negative test",
	  "I think that is ok.",
	  "Hmmm I don't think I change anything here. Not sure why there is a diff",
	  "Thanks for this!",
	  "How is this related to the PR?",
	  "How did you arrive at this algorithm?",
	  "I didn't :) Completely forgot to run clang-format...",
	  "Do you mean the following?",
	  "No, will remove, thanks",
	  "Ah, good spot!",
	  "This is a good comment. Let's change this in another patch. Thanks.",
	  "Done! I have just pushed an updated patch, so it's ready to be merged if there are no more comments.",
	  "Ahh sorry about that. Thanks for clarifying",
	  "Updated, thanks!",
	  "Good point, done.",
	  "Yea, this makes sense to harmonize. I'll try to come back to this one later, or write a good first issue for cleaning this up.",
	  "manager",
	  "DOCUMENTME :)",
	  "It does!",
	  "these are unused",
	  "Deleted explicit output specification in 78cf14fa66fd9817a63537d37f0bc2078967a08d, thanks. Also applied to #113817",
	  "Thanks for the quick review!",
	  "I agree, this is definitely broken.",
	  "this also sets the debug info where it didn't set it before which is good to fix as well, thanks.",
	  "Done. Thanks. I checked that the rendered html looked ok.",
	  "Thanks. I forgot we had that. Its much nicer.",
	  "Please drop trivial braces here and below.",
	  "Ah got it. Sorry about that. Thanks for the suggested change",
	  "@ojhunt",
	  "Thanks, Digger. I have added this at the end of the test case.",
	  "That's quite interesting case. Will add your example to negatives. Thanks",
	  "Thanks for your comment, a new commit has been added.",
	  "This sounds good to me, thank you!",
	  "TODO: Fix",
	  "Oh, that’s very true. Thanks for the clarification!",
	  "Thanks for the link. I'll try to catch up on the updates ",
	  "Done in 740f05545150fb01cfca8c16da50c956b4f30959, thanks!",
	  "I removed this test case for now. Thanks for pointing this out.",
	  "Fixed by https://github.com/llvm/llvm-project/pull/115677",
	  "I fixed this in 528bcf3a55ca520c31c77ed5fbacf09bff8f39ec",
	  "(And thanks for the extended test case!)",
	  "Very well, perhaps worth leaving a TODO.",
	  "Thanks for the suggestion. This is a feature I was not aware of in Python.",
	  "Thanks for checking.",
	  "Hi Ivan. Thanks for pointing this out. I will create a follow up PR to clean up and remove this duplication",
	  "Oh okay. I understand. Thanks for this! I've addressed it - please take a look.",
	  "Okay, this seems like a code smell to me, but it's reasonable enough. Thanks!",
	  "is this needed?",
	  "Thanks, done in [`@find_first_of_i8_multi_exit`](https://github.com/llvm/llvm-project/pull/101976/commits/6d1755189549f3f6dd804d98810cbc374cd087a8#diff-f256205074dbd8200178875fe608f7daf7a0871a9e4bea54d8215524588aca76R325).",
	  "remaining",
	  "I think I like that much better, yes. Thanks!",
	  "Thanks, that is a good idea!",
	  "done in latest commit, thx",
	  "thx",
	  "Thanks, have moved this into a helper function :)",
	  "I need to update these comments.",
	  "removed and cleaned all",
	  "Yes, that's a bugfix.",
    "removed justification",
	  "Thanks for pointing that out! I was not aware of that appraoch.",
	  "Can avoid reaching here?",
	  "yes",
	  "Yes",
	  "No",
	  "no",
	  "Fixed",
	  "ah",
	  "oh",
	  "ok",
	  "OK",
	  "Ok",
	  "Ah",
	  "Done",
	  "done",
	  "Done.",
	  "done.",
	  "good",
	  "Good",
	  "neat",
	  "Neat",
	  "missed",
	  "Missed",
	  "Nope",
	  "nope",
	  "Yeah",
	  "yeah",
	  "anyway",
	  "Anyway",
	  "Anyways",
	  "anyways",
	  "Ping",
	  "ping",
	  "right",
	  "please",
	  "Please",
	  "looks",
	  "Looks",
	  "follow",
	  "PR",
	  "pr",
	  "Pr",
	  "catching",
	  "working",
	  "Oh",
	  "sense",
	  "Sense",
	  "sound",
	  "sounds",
	  "bad",
	  "Bad",
	  "good.",
	  "Good.",
	  "thx",
	  "todo",
	  "ToDo",
	  "TODO",
    "That's weird.",
	  "Updated to named values.",
	  "ditto. Leave below unchanged",
	  "ditto",
	  "ditto, the same below.",
	  "Removed and updated.",
	  "updated",
	  "Removed",
	  "Why does this need moving?",
	  "Hi, Matt, I have updated it.",
	  "updated",
	  "wrong",
	  "works",
	  "Hi",
	  "hi",
	  "Ditto about adding comment",
	  "Made the comment very much more specific",
	  "This is a very clever way of capturing what's going! Well done and thank you",
	  "Well",
	  "better",
	  "FIXME",
	  "Oops, that was a testing message I left in. I've deleted it now.",
	  "copy",
	  "addressed",
	  "description",
	  "read",
	  "Thank you for explanation!",
	  "ditto above.  cheap type (2 words)",
	  "ditto, I think this is also doable and will address it in the follow-up PR.",
	  "That is what happens now.",
	  "look",
	  "This is already stated above.",
	  "already",
	  ":D",
	  "I'd prefer having this explicit.",
	  "Sorry, that's some private note for myself and which has been done.",
	  "Do we need to do that?",
	  "we",
	  "Same comments here",
	  "comments",
	  "Ditto. there must be a better-named function for this",
	  "Not here",
	  "Not",
	  "Moved to header.Moved to header.",
	  "yep, this case actually happens a lot in our downstream projects.   I planed to handle it in a follow-up patch: https://github.com/llvm/llvm-project/pull/105383",
	  "understood",
	  "I am not sure I understood this, sorry.",
	  "Check these first?",
	  "Check",
	  "agree",
	  "I agree and have made the change",
	  "done, moved after line 108.",
	  "line",
	  "Adopted where applicable.",
	  "It is not only C++, but also works in C I think?",
	  "C++",
	  "C",
	  "Also here -- could you re-indent?",
	  "Could please add some comments?",
	  "typo",
	  "Addressed",
	  "nevermind, you caught this already.",
	  "Dead code?",
	  "ditto, the same below.",
	  "Forgot",
	  "I don't think we have one.",
	  ":(",
	  ":)",
	  "itto for [LWG3862](https://cplusplus.github.io/LWG/issue3862):",
	  "(ditto, here and below)",
	  "Thanks a lot for the explanations and clarifications.",
	  "Ditto for [LWG3948](https://cplusplus.github.io/LWG/issue3948) (assuming the #99915 will be merged first)",
	  "Nice types.",
	  "Nice",
	  "point",
	  "Ditto for [LWG3769](https://cplusplus.github.io/LWG/issue3769):",
	  "Great",
	  "catch",
	  "Is this change desirable.",
	  "change",
	  "Well, it is right, but I think that this approach is even better.",
	  "better",
	  "75b5ab27a41f",
	  "You don't need that anymore",
	  "You",
	  "Thanks",
	  "Same as above",
	  "Same",
	  "fine",
	  "I think it's fine",
	  "do.",
	  "Will do.",
	  "ditto about code style",
	  "duplicate",
	  "Ditto. It can be filled with a calculated value when it's omitted.",
	  "@arsenm Here.",
	  "@arsenm",
	  "Copy paste comment",
	  "Ok, I moved the code to the `include/cmath` header (see 94435bec53e4b1e54d948869cb6ba15012e4570f).",
	  "It should work, what's the error you got?",
	  "error",
	  "yea that was an error in my logic",
	  "Yeah fair enough, just this case is not relaxing the constraint, its tightening it.",
	  "logic",
	  "Indeed",
	  "Nvm",
	  "Nvm.",
	  "Nvm. Removed this logic.",
	  "rid",
	  "Deleted",
	  "Deleted.",
	  "Yep",
	  "Commuted tests?",
    "Add newline",
	  "Yeah, that does sound like a problem.",
	  "Yeah,",
	  "problem",
	  "problem.",
	  "Most cases are simply grouped.",
	  "cases",
	  "Thank you @CarolineConcatto for reviews. I have updated patch. Could you please review again?",
	  "I see.",
	  "Thanks! I blindly copied existing code however should've reread it.",
	  "Sorry for the high latency!",
	  "Sorry",
	  "sorry",
	  "Thanks, I think I understand where the confusion is coming from. Correct me if I'm wrong ...",
	  "thank you Martin! for the detailed explanation. i concur with you and Julian now",
	  "added tests for v4i16, v4f16, v4bf16, v2bf16",
	  "I'll add them here.",
	  "I'll",
	  "DEPENDS",
	  "Actually it caught some, though I haven't looked into all:",
	  "I took some advice from this change and reworded this paragraph. Thank you!",
	  "this isn't needed",
	  "needed",
	  "helpful",
	  "helpful.",
	  "I think they're helpful.",
	  "I",
	  "sorry, this was in some internal non-public bots. yes that commit fixes this, thanks for the pointer",
	  "ACK",
	  "ACK.",
	  "Yes, I forgot to remove this when I fixed the tests. Thanks for finding it.",
	  "finding",
	  "5dac5006c692",
	  "ok, I thought of this too. I just wanted to make sure before choosing a way. Thanks Alexey.",
	  "Makes sense, thanks! I've made a few suggestion for additional comments ^^^.",
	  "note",
	  " Added release note.",
	  "release",
	  "Docstring here.",
	  "Hi Jonathan,",
	  "Accident?",
	  "Does this LGTY?",
	  "Does",
	  "LGTY",
	  "LGTY?",
	  "helpful",
	  "veryvery",
	  "comment",
	  "Thanks,",
	  "Thanks, I added a comment to the function.",
	  "Thanks for the comment, I'll look to expand this test with your suggestions.",
	  "Okay",
	  "Okay,",
	  "okay",
	  "okay,",
	  "This was just moved too.",
	  "This",
	  "moved",
	  ")",
	  "too",
	  "Here",
	  "Here too.",
	  "indeed",
	  "indeed",
	  "beneficial",
	  "Thanks for this suggestion! It would be very beneficial indeed.",
	  "Thanks, fixed in https://github.com/steakhal/llvm-project/commit/3b2d3231eb29dddf8f024c6dee0f5d8ce1b1d261.",
	  "feedback",
	  "feedback!",
	  "We don't have a story for debug info yet :(",
	  "Got",
	  "it",
	  "Got it, changed.",
	  "changed",
	  "changed.",
	  "correct.",
	  "test",
	  "Indeed",
	  "Indeed,",
	  "Indeed, thank you for reporting this.",
	  "reporting",
	  "Incorrect file name",
    "Nice",
    "catch!",
    "Thanks",
    "Thank",
    "Nice catch! Thank you!",
    "I see. Thanks."
    "I don't understand the code with the change",
    "Thanks for making the update here.",
    "Debugging...",
    "Debugging",
    "Thanks for the reply!",
    "Updated, thanks!",
    "Looks better to me.",
    "me.",
    "me",
    "oversight",
    "adjust",
    "Thanks for filing the issue.",
    "Will adjust separately.",
    "sure, sounds good.",
    "Oh my...",
    "Hmm.. I went for this approach because of how the IR looked.  Maybe I missed something here.",
    "That's horrible, but good catch. In that case I guess we can keep the current implementation, it's very reasonable.",
    "You're correct. I guess it must have moved while I was refactoring things..",
    "Added some in b5afda8d760998641cf08a6d229252924b0ad146",
    "Yes, I think with the edit to the previous lines it's easier to follow.",
    "I know this is a TODO, but the language is a bit awkward.",
    "I think this is okay then. I don't think it is worth adding a new flag.",
    "Yeah, that was a total oversight on my part.",
    "Hmm.. I went for this approach because of how the IR looked.  Maybe I missed something here.",
	  "That's horrible, but good catch. In that case I guess we can keep the current implementation, it's very reasonable.",
	  "You're correct. I guess it must have moved while I was refactoring things..",
	  "Added some in b5afda8d760998641cf08a6d229252924b0ad146",
	  "Yes, I think with the edit to the previous lines it's easier to follow.",
	  "I know this is a TODO, but the language is a bit awkward.",
	  "I think this is okay then. I don't think it is worth adding a new flag.",
	  "Yeah, that was a total oversight on my part.",
	  "Thanks, good point. That was also changed in the original PR so I will revert that too. I wonder if it makes more sense to do a full revert and reland with the right changes instead. But since the PR is 1 year old it might be tricky.",
	  "ohh! sorry couldn't find it. can u specify where it is ? and do i need to undo the formatting i think that is automatically done by the editor i am using",
	  "I'll remove that option since we don't really need it for the test case.",
	  "I'd add a TODO to move this to the versioned namespace. We can do that in a follow-up patch.",
	  "Fixed in [a891346](https://github.com/llvm/llvm-project/pull/132994/commits/a891346a8524a414adcd2f33e63e06ab8e39a732)",
	  "Agreed, that's probably easier and less invasive.",
	  "so this guideline only applies when introducing a new macro.",
	  "I wonder if these TODOs are the best way to remember about these tasks. I suspect a comment in the issue that makes `std::deque` constexpr would also help, potentially.",
    "How embarrassing, I ran the script before I changed the version. Should be correct now, sorry! And thank you for reviewing :)",
	  "oh yeah sorry! i completely missed that it could be negative as wel",
	  "fixed in [4c9b493a](https://github.com/llvm/llvm-project/pull/132484/commits/4c9b493a2c7b993e4b742e57d08d6925a866bf5c)",
	  "Please add the comments to explain how we derived the exponent computations.",
	  "Filled in.",
	  "fixed in [00b5943c](https://github.com/llvm/llvm-project/pull/126303/commits/00b5943cb279d64e4d15849ca75a453afd417e54)",
	  "What does this file use from stddef.h? Please explicitly include libc/hdr/types/size_t.h for size_t.",
	  "ah.. sorry about that! fixed in [caa32e6e](https://github.com/llvm/llvm-project/pull/126291/commits/caa32e6e67e9be05a5e4a317e92209df69173bcd)",
	  "resolved in [caa32e6e](https://github.com/llvm/llvm-project/pull/126291/commits/caa32e6e67e9be05a5e4a317e92209df69173bcd)",
	  "Should hopefully be fixed by 2d6330f83a64a414f83d647bba7f23928f66aa5c",
	  "fixed all these in [52a98bb](https://github.com/llvm/llvm-project/pull/125704/commits/52a98bbcac609fc164fb3e068b47cf3b11a35858)",
	  "False dependency, remove.",
	  "Thanks for this! I have fixed the idiv-support condition now.",
	  "Fixed in [6fff293](https://github.com/llvm/llvm-project/pull/125638/commits/6fff293f7a9e6a981ba2ff59397cfaa440bd011d).",
	  "This should be fixed with https://github.com/llvm/llvm-project/pull/125596 . We can either leave a TODO to drop the dynamic case when the PR lands or wait a bit and land this after.",
	  "Should fix doing that there?",
	  "Resolved in [475945d9](https://github.com/llvm/llvm-project/pull/125356/commits/475945d9556edbe496dbd43af2461b52a51edf00)",
	  "fixed in [9b499bcb](https://github.com/llvm/llvm-project/pull/125356/commits/9b499bcb5a1894b4991c14885cd514746c6c634a)",
	  "Thanks. Fixed in [459d2d5](https://github.com/llvm/llvm-project/pull/125307/commits/459d2d5ea7f803cc6553b7d9007283281263f1fe)",
	  "Great point. Yeah I think it could have done. I have fixed this in https://github.com/llvm/llvm-project/pull/125307/commits/459d2d5ea7f803cc6553b7d9007283281263f1fe",
	  "Thanks. Fixed in [459d2d5](https://github.com/llvm/llvm-project/pull/125307/commits/459d2d5ea7f803cc6553b7d9007283281263f1fe)",
	  "I've fixed the build failure with https://github.com/llvm/llvm-project/commit/8578b816fa9050c33561f06d631459e12645953a. Thanks!",
	  "Fixed by https://github.com/llvm/llvm-project/commit/381416a8c7e0e8fc8b12c83c6c856b8ef7c4d8a8",
	  "Should be fixed now. I also moved the formatting to a separate commit.",
	  "Thanks, fixed in https://github.com/llvm/llvm-project/pull/124421/commits/56c0267f91967d6db9f9e9f5f93ad63343464230",
	  "No worries, fixed in https://github.com/llvm/llvm-project/pull/124036/commits/56c7755d0e1dc4c36f53e9177654b56ca06104ec",
	  "I updated it in https://github.com/llvm/llvm-project/pull/124019/commits/ca35ec29e81dfd3222d4ebba91937c96b5080f91",
	  "Fixed in https://github.com/llvm/llvm-project/pull/124019/commits/4325873687bb18cd9000a12b369e593667c99f29",
	  "Yes, bugs cause other bugs and all the use points need to be fixed",
	  "I applied your suggested fixed together with Eugene's to my pr https://github.com/llvm/llvm-project/pull/122957",
	  "Fixed in: [67ed339cb821](https://github.com/llvm/llvm-project/pull/122835/commits/67ed339cb8213aaa7a8bb83896cf707b7119d619)",
	  "Fixed in: [be54a010ae13](https://github.com/llvm/llvm-project/pull/122835/commits/be54a010ae13f885c61a605322cf5dce98bc7ae2)",
	  "oops sorry for missing that, should be fixed with a2063ba7ffdbbb4faf5da5f32739ab761c2e4289",
	  "Nice, fixed. Once https://github.com/llvm/llvm-project/pull/119261 lands we'll be able to simply iterate over the functions and this won't even be needed.",
	  "fixed in https://github.com/llvm/llvm-project/commit/0ee8d8cd4b3d61fc6cf6e740a54dd5a23c921048!",
	  "fixed in https://github.com/llvm/llvm-project/pull/121839/commits/3ce51118035f1f84ad02898858c95021ff6420d9, thx",
	  "Thanks for the review! ",
    "@boomanaiden154 specifically suggested this [here](https://github.com/llvm/llvm-project/pull/121839#discussion_r1925920983), but I'm happy to change it to FIXME if you prefer.",
 	  "@AaronBallman could you take a look at this issue? thanks",
 	  "yes, feel free to submit a new pr. thanks",
 	  "@antangelo thanks. I've removed the assert in favor of a condition and added additional tests.",
 	  "@zygoloid thank you for the review! I pushed your suggestion and updated PR summary",
 	  "thanks for the feedback. I've updated it to use an explicit type.",
 	  "@AaronBallman thanks for the detailed feedback. I've updated the tests to cover all the provided cases.",
 	  "Thanks for the feedback. I've added changes.",
 	  "@Fznamznon Thanks for the review. I've added a comment.",
    "Sorry, I didn't notice that you replied to me on the issue. I only checked my previous issue after submitting the pull request. I'm very sorry. I will reopen this PR now.",
    "I have reverted the branch and reopened this PR, thank you very much for your reply",
    "I have modified this point. Thank you again for your suggestion. It is really necessary.",
    "Hi, thank you very much for your suggestion. I have modified the code. You can check the latest commit. If possible, please give LGTM. Thank you.",
    "I guess whether we want to link Support into flang-rt may need a broader discussion.  Until we sort it out, we can keep your function.",
    "I've done something here, but I'm not sure it's exactly what we want. Let me know what you think.",
    "I think I'm ok with it for the purposes of this patch. I may see about generating a better error that doesn't point to a spec.",
    "@MaskRay, thank you very much for comment, I'm sorry, I tried to reproduce test fail using check-llvm but without success, may I ask                                   you for advice about how to reproduce the problem?",
    " I'm sorry, that was some misunderstanding on my part. I created PR https://github.com/llvm/llvm-project/pull/121073, could you PTAL?",
    "I hoped I could get away with referring to Zc, but I will update it.",
    "I've done something here, but I'm not sure it's exactly what we want. Let me know what you think.",
    "I'll leave the choice up to you!  Change all of them would be my preference, but I'd like consistency between the three.",
    "Can you keep the formatting here and in the rest of the file?",
    "I don't think it matters a lot. ill formed conveys it's a standard requirement pretty well",
    "Though we probably don't need this warning anymore but this is really a great catch of wording issues!",
    "Addressed in e273a996854cb3256cfeed832c3f16ff6fd0f534, thank you for the feedback!",
    "Are these useful? The option is defaulted to true anyway right? And it's likely to land in 26 in a few weeks",
    "I'll leave the choice up to you!  Change all of them would be my preference, but I'd like consistency between the three.",
    "Still want this combined/generalized.  These are incredibly similar in both use and content.",
    "will remove",
    "Solution you suggest makes sense to me, I am OK doing it in separate patch.",
    "Thanks, I revived this patch from an old local branch I had and went a bit fast.",
    "The name was for debugging yes. However, it is actually the functional alias.",
    "[ec540b6](https://github.com/llvm/llvm-project/pull/89173/commits/ec540b6f4cea6a9df180d4dcd5b54da1ec4b149f)",
    "It should.I did test it with other changes to ensure it works properly. Somehow final cleanup (removing other stuff in the .td file) made a mistake. Fixed it now.",
    " To be honest, I wrote this >1 year ago, so I don't really remember why I chose to do it this way. I reworked it to use a different ISD node for dynamic VGPRs, I hope it's cleaner this way.",
    "These could use some more wrapping/reformatting.",
    "Understood, thank you. At times wrangling tablegen to do what one wants takes an unreasonable amount of time :(",
    " Good suggestion. I know it must be a way to simplify it and I just didn't do it yet. Will give a try later.",
    "Agreed. I'll commit this as is and then try to replace with an IR test as a followup.",
    "This case shouldn't happen. Ideally the verifier would reject it",
    "I think it's before this patch. This overall is not complicated so let me add more cases here.",
    "Right. Let me fix this case. Missed this case when changed to lookthroughCopylike",
    "Can you explain how the coalescer is relevant here? The test only runs phi-node-elimination.",
    " Hi Matt. Do you suggest to simplify the test code and make it smaller?",
    "Should keep both probably",
    "open an issue to track this https://github.com/llvm/llvm-project/issues/111205",
    "This case still looks wrong, but we don't actually want this to ever be produced.",
    "OK I just noticed you have approved this PR. I will commit it first and will look into VOP3 commuting opportunity later.",
    "Could you please rebase on fresh main, this changes must be added by https://github.com/llvm/llvm-project/commit/52639d69acbed0e49fd855c8c04cd9307405e2e6",
    "hopefully the latest commit has the use case youre looking for",
    "Ah, okay, I think there's a small tweak to the example and I'll be happy. I'll suggest it below.",
	"It always good to take rather than leave ;) I haven't got used to this syntax and I'd leave it :(",
    
        
    
        
    

]
SHORT_MAX_LEN: Dict[str, int] = {"thanks": 59, "fixed": 125, "Thanks": 59, "yes": 59, "Yes": 59, "No": 59, "no":59, "Fixed": 112, "ah": 59, "oh": 59, "ok": 59, "OK": 59, "Ok": 59, "Ah": 59, "Done": 59, "done": 59, "good": 59, "Good": 59, "neat": 59, "Neat": 59, "missed": 59, "Missed": 59, "Nope": 59, "nope": 59, "Yeah": 59, "yeah": 59, "anyway": 59, "Anyway": 59, "Anyways": 59, "anyways": 59, "Ping": 59, "ping": 59, "right": 59, "please": 59, "Please": 59, "looks": 59, "Looks": 59, "follow": 59, "PR": 59, "pr": 59, "Pr": 59, "catching": 59, "working": 59, "Oh": 59, "sense": 59, "Sense": 59, "sound": 59, "sounds": 59, "bad": 59, "Bad": 59, "good.": 59, "Good.": 59, "thx": 59, "todo": 59, "ToDo": 59, "TODO": 59, "Done.": 59, "done.": 59, "apologies": 59, "I": 59, "weird": 59, "ditto": 35, "done": 59, "updated": 120, "Removed": 59, "wrong": 59, "works": 59, "Hi": 59, "hi": 59, "comment": 59, "Well": 59, "better": 59, "FIXME": 59, "Oops": 59, "copy": 59, "addressed": 59, "description": 59, "read": 59, "Thank": 59, "happens": 59, "look": 59, "already": 59, ":D": 59, "Sorry": 59, "we": 59, "comments": 59, "Not": 59, "understood": 59, "Check": 59, "agree": 59, "line": 59, "C++": 59, "C": 59, "typo": 59, "Addressed": 59, "Dead code": 59, "Forgot": 59, ":(": 59, ":)": 59, "Nice": 59, "point": 59, "Great": 59, "catch": 59, "change": 59, "better": 59, "You": 59, "Same": 59, "fine": 59, "do": 59, "do.": 59, "duplicate": 59, "@arsenm": 59, "error": 59, "logic": 59, "Indeed": 59, "Nvm": 59, "Nvm.": 59, "rid": 59, "Deleted": 59, "Deleted.": 59, "done": 59, "Yep": 59, "newline": 59, "Yeah,": 59, "problem": 59, "problem.": 59, "cases": 59, "sorry": 59, "I'll": 59, "DEPENDS": 59, "needed": 59, "helpful": 59, "helpful.": 59, "I": 59, "ACK": 59, "ACK.": 59, "finding": 59, "Accident?": 59, "Does.": 59, "release": 59, "LGTY": 59, "LGTY?": 59, "helpful": 59, "very": 59, "comment": 59, "Thanks,": 59, "Okay": 59, "Okay,": 59, "okay,": 59, "okay,": 59, "This": 59, "moved": 59, "too": 59, "Here": 59, "indeed": 59, "indeed.": 59, "beneficial": 59, "feedback": 59, "feedback!": 59, "Got": 59, "it": 59, "changed": 59, "changed.": 59, "correct.": 59, "correct": 59, "test": 59, "Indeed": 59, "Indeed,": 59, "reporting": 59, "Nice": 59, "catch!": 59, "Debugging": 59, "me.": 59, "me": 59, "adjust": 59, "oversight": 59, "Agreed": 59, "probably": 59, "that's": 59, "deasierone": 59, "resolved": 120, "Resolved": 120}
# ───────────────────────────────────────────────────────────────────────

# output locations
DEBUG_DIR = "debugging_files"
TSV_DIR   = "."

DATA_FILE = "preprocessed_data.json"

DROPPED_FILE = os.path.join(DEBUG_DIR, "dropped_comments.txt")
DIFF1_FILE   = os.path.join(DEBUG_DIR, "diffs_label1.txt")   # positives
DIFF0_FILE   = os.path.join(DEBUG_DIR, "diffs_label0.txt")   # negatives

CODESPLIT       = "<CODESPLIT>"
TRAIN_RATIO     = 0.80
DEV_RATIO       = 0.10
SEED            = 42
WINDOW_SIZE     = 200
OVERLAP         = 50
SUGG_OVERSAMPLE = 2          # stays ≥1 for training
LENGTH_THRESHOLD = 59

# ───────── regex helpers (unchanged) ─────────
_TRIVIAL_RE = [
    re.compile(r"^\s*(?:lgtm|ship it|\+1)[.!]*$", re.I),
    re.compile(r"^\s*(?:thanks?|thank you)[.!]*$", re.I),
]
def is_trivial(t: str) -> bool:
    t = (t or "").strip()
    return len(t) < 5 or not re.search(r"[A-Za-z0-9]", t) or any(p.match(t) for p in _TRIVIAL_RE)

def normalize(s: str) -> str:
    return re.sub(r"\W+", " ", s).strip().lower()

GENERIC_NORMS = [normalize(p) for p in GENERIC_EXAMPLES]
SHORT_MAX_LEN = {normalize(k): v for k, v in SHORT_MAX_LEN.items()}
FUZZY_THRESHOLD, TYPO_THRESHOLD = 92, 80

def is_generic(c: str) -> bool:
    txt = normalize(c)
    for pat in GENERIC_NORMS:
        maxlen = SHORT_MAX_LEN.get(pat)
        if maxlen and pat in txt.split() and len(txt) <= maxlen:
            return True
        if txt == pat:
            return True
        delta = max(2, min(4, int(len(pat) * 0.2)))
        if abs(len(txt) - len(pat)) <= delta and \
           fuzz.token_set_ratio(txt, pat) >= TYPO_THRESHOLD:
            return True
        if len(txt) > len(pat) + delta and fuzz.ratio(txt, pat) >= FUZZY_THRESHOLD:
            return True
    return False

SUGGESTION_RE = re.compile(
    r"\b(please|can you|ensure|should|could|recommend|consider|need to|we can|can|"
    r"let'?s|remove|add|refactor|update|optimi[sz]e)\b", re.I)
def is_suggestion(c: str) -> bool: return bool(SUGGESTION_RE.search(c))

TECH_RE = re.compile(r"[`\w]+\.\w+|`[^`]+`|/\w+|::|\b[A-Za-z_]\w*\(\)", re.X)
def has_technical_reference(c: str) -> bool: return bool(TECH_RE.search(c))

DESIGN_RE = re.compile(
    r"\b(Is it really worth|Why can'?t|Do we need|Should we|Perhaps we should|Why not)\b", re.I)
def is_design(c: str) -> bool: return bool(DESIGN_RE.search(c))

# ───────── diff windows ─────────
def sliding_windows(diff: str):
    toks = diff.split()
    if len(toks) <= WINDOW_SIZE:
        yield 1, " ".join(toks)
    else:
        step = WINDOW_SIZE - OVERLAP
        for idx, s in enumerate(range(0, len(toks), step), start=1):
            yield idx, " ".join(toks[s:s + WINDOW_SIZE])
            if s + WINDOW_SIZE >= len(toks):
                break

# ───────── pretty writer ─────────
def pretty(fp, tag, prn, win_idx, file_path, labels, diff_win, comment):
    fp.write(f"===== {tag} (PR {prn} • window #{win_idx}) =====\n")
    fp.write(f"FILE  : {file_path}\n")
    fp.write(f"LABEL : {labels or '(none)'}\n")
    fp.write("---------------------------------------- DIFF\n")
    fp.write(diff_win.rstrip() + "\n")
    fp.write("--------------- COMMENT\n")
    fp.write(comment.strip() + "\n")
    fp.write("============================================================\n")

# ───────── debug-file handles & dedup sets ─────────
os.makedirs(DEBUG_DIR, exist_ok=True)
_dropped_fp = open(DROPPED_FILE, "w", encoding="utf-8")
_diff1_fp   = open(DIFF1_FILE, "w", encoding="utf-8")
_diff0_fp   = open(DIFF0_FILE, "w", encoding="utf-8")
atexit.register(lambda: (_dropped_fp.close(), _diff1_fp.close(), _diff0_fp.close()))

_seen_drop : Set[str]            = set()
_seen_diff1: Set[tuple]          = set()   # (prn, comment_clean)
_seen_diff0: Set[tuple]          = set()   # (prn, comment_clean)
# ───────── build positives ─────────
def make_positives(rec):
    out = []
    prn  = str(rec.get("pr_number", ""))
    fn   = rec.get("filename", "")
    lbls = rec.get("labels", "")
    diff = (rec.get("diff_text") or "").strip()
    sugg = (rec.get("suggestion_text") or "").strip()
    comm = (rec.get("comment_text") or "").strip()
    commenter = rec.get("commenter", "")

    if not diff:
        return out

    prefix = f"[FILE]{fn} [LABEL]{lbls} "

    for w_idx, win in sliding_windows(diff):
        windowed = prefix + win

        if sugg:
            for _ in range(SUGG_OVERSAMPLE):
                out.append((1, prn, commenter, windowed, sugg))
                key = (prn, sugg.strip())
                if key not in _seen_diff1:
                    pretty(_diff1_fp, "POS", prn, w_idx, fn, lbls, win, sugg)
                    _seen_diff1.add(key)

        if comm and comm != sugg and not is_trivial(comm):
            if is_generic(comm):
                clean = comm.replace("\n", " ⏎ ")
                if clean not in _seen_drop:
                    _dropped_fp.write(clean + "\n")
                    _seen_drop.add(clean)
                continue
            if len(comm) <= LENGTH_THRESHOLD or \
               has_technical_reference(comm) or \
               is_suggestion(comm) or \
               is_design(comm):
                out.append((1, prn, commenter, windowed, comm))
                key = (prn, comm.strip())
                if key not in _seen_diff1:
                    pretty(_diff1_fp, "POS", prn, w_idx, fn, lbls, win, comm)
                    _seen_diff1.add(key)
            else:
                clean = comm.replace("\n", " ⏎ ")
                if clean not in _seen_drop:
                    _dropped_fp.write(clean + "\n")
                    _seen_drop.add(clean)
    return out

# ───────── sample negatives ─────────
def sample_negatives(pos):
    negs, idxs = [], list(range(len(pos)))
    for i in tqdm(idxs, desc="Sampling negatives"):
        _, pr_i, _, diff_i, _ = pos[i]
        while True:
            j = random.choice(idxs)
            if j != i and pos[j][1] != pr_i:
                break
        _, _, commenter_j, _, text_j = pos[j]
        negs.append((0, pr_i, commenter_j, diff_i, text_j))
    return negs

# ───────── TSV writer ─────────
def write_tsv(rows, name):
    path = os.path.join(TSV_DIR, name)
    with open(path, "w", encoding="utf-8") as f:
        for lbl, prn, com, diffw, commw in rows:
            d = diffw.replace("\n", " ")
            c = commw.replace("\n", " ")
            f.write(f"{lbl}{CODESPLIT}{prn}{CODESPLIT}{com}"
                    f"{CODESPLIT}{d}{CODESPLIT}{c}\n")

# ───────── main ─────────
def main():
    random.seed(SEED)
    with open(DATA_FILE, encoding="utf-8") as f:
        records = json.load(f)

    positives = []
    for rec in tqdm(records, desc="Building positives"):
        positives.extend(make_positives(rec))
    negatives = sample_negatives(positives)

    # pretty negatives (dedup)
    for idx, (_, prn, _, diffw, commw) in enumerate(negatives, start=1):
        try:
            _, rest = diffw.split("[FILE]", 1)
            fp, r   = rest.split(" ", 1)
            lbl_tag, win = r.split(" ", 1)
            lbls = lbl_tag.replace("[LABEL]", "")
        except ValueError:
            fp, lbls, win = "(unknown)", "", diffw
        key = (prn, commw.strip())
        if key not in _seen_diff0:
            pretty(_diff0_fp, "NEG", prn, idx, fp, lbls, win, commw)
            _seen_diff0.add(key)

    # shuffle & split → TSVs
    all_rows = positives + negatives
    random.shuffle(all_rows)
    n = len(all_rows)
    tr, dv = int(n * TRAIN_RATIO), int(n * DEV_RATIO)
    write_tsv(all_rows[:tr],          "train.tsv")
    write_tsv(all_rows[tr:tr + dv],   "dev.tsv")
    write_tsv(all_rows[tr + dv:],     "test.tsv")

    print("✔ process_data_pr.py complete")

if __name__ == "__main__":
    main()
